'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSSMSMasivos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SMSMasivosAPISoap", [Namespace]:="http://servicio.smsmasivos.com.ar/ws/")>  _
    Partial Public Class SMSMasivosAPI
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecibirSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.EnvioDeNotificaciones.My.MySettings.Default.EnvioDeNotificaciones_WSSMSMasivos_SMSMasivosAPI
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarSMSCompleted As EnviarSMSCompletedEventHandler
        
        '''<remarks/>
        Public Event RecibirSMSCompleted As RecibirSMSCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicio.smsmasivos.com.ar/ws/EnviarSMS", RequestNamespace:="http://servicio.smsmasivos.com.ar/ws/", ResponseNamespace:="http://servicio.smsmasivos.com.ar/ws/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarSMS(ByVal usuario As String, ByVal clave As String, ByVal numero As Long, ByVal texto As String, ByVal test As Boolean) As String
            Dim results() As Object = Me.Invoke("EnviarSMS", New Object() {usuario, clave, numero, texto, test})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarSMSAsync(ByVal usuario As String, ByVal clave As String, ByVal numero As Long, ByVal texto As String, ByVal test As Boolean)
            Me.EnviarSMSAsync(usuario, clave, numero, texto, test, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarSMSAsync(ByVal usuario As String, ByVal clave As String, ByVal numero As Long, ByVal texto As String, ByVal test As Boolean, ByVal userState As Object)
            If (Me.EnviarSMSOperationCompleted Is Nothing) Then
                Me.EnviarSMSOperationCompleted = AddressOf Me.OnEnviarSMSOperationCompleted
            End If
            Me.InvokeAsync("EnviarSMS", New Object() {usuario, clave, numero, texto, test}, Me.EnviarSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarSMSCompleted(Me, New EnviarSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicio.smsmasivos.com.ar/ws/RecibirSMS", RequestNamespace:="http://servicio.smsmasivos.com.ar/ws/", ResponseNamespace:="http://servicio.smsmasivos.com.ar/ws/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecibirSMS(ByVal usuario As String, ByVal clave As String, ByVal origen As String, ByVal solonoleidos As Boolean, ByVal marcarcomoleidos As Boolean) As clsRespuesta()
            Dim results() As Object = Me.Invoke("RecibirSMS", New Object() {usuario, clave, origen, solonoleidos, marcarcomoleidos})
            Return CType(results(0),clsRespuesta())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecibirSMSAsync(ByVal usuario As String, ByVal clave As String, ByVal origen As String, ByVal solonoleidos As Boolean, ByVal marcarcomoleidos As Boolean)
            Me.RecibirSMSAsync(usuario, clave, origen, solonoleidos, marcarcomoleidos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecibirSMSAsync(ByVal usuario As String, ByVal clave As String, ByVal origen As String, ByVal solonoleidos As Boolean, ByVal marcarcomoleidos As Boolean, ByVal userState As Object)
            If (Me.RecibirSMSOperationCompleted Is Nothing) Then
                Me.RecibirSMSOperationCompleted = AddressOf Me.OnRecibirSMSOperationCompleted
            End If
            Me.InvokeAsync("RecibirSMS", New Object() {usuario, clave, origen, solonoleidos, marcarcomoleidos}, Me.RecibirSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecibirSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecibirSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecibirSMSCompleted(Me, New RecibirSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicio.smsmasivos.com.ar/ws/")>  _
    Partial Public Class clsRespuesta
        
        Private numeroField As Long
        
        Private textoField As String
        
        Private fechaField As Date
        
        Private idsmsField As Long
        
        Private idinternoField As String
        
        '''<remarks/>
        Public Property numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property texto() As String
            Get
                Return Me.textoField
            End Get
            Set
                Me.textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idsms() As Long
            Get
                Return Me.idsmsField
            End Get
            Set
                Me.idsmsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idinterno() As String
            Get
                Return Me.idinternoField
            End Get
            Set
                Me.idinternoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub EnviarSMSCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RecibirSMSCompletedEventHandler(ByVal sender As Object, ByVal e As RecibirSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecibirSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsRespuesta()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsRespuesta())
            End Get
        End Property
    End Class
End Namespace
